# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dzTFXcYDt8m-lwBVcUuP2PxnKgmpXkTI
"""

from flask import Flask, jsonify
import regex as re
app = Flask(__name__)

@app.route('/', methods=['GET'])
def hello_world():
  json_response = {
      'status_code' : 200,
      'description' : "Menyapa Hello World",
      'data' : "Hello World"
  }

  response_data = jsonify(json_response)
  return response_data

@app.route('/text', methods=['GET'])
def text_clean():
  json_response = {
      'status_code' : 200,
      'description' : "original text",
      'data' : ("Halo, apa kabar semua")
  }

  response_data = jsonify(json_response)
  return response_data

@app.route('/text-clean', methods=['GET'])
def text():
  json_response = {
      'status_code' : 200,
      'description' : "original text",
      'data' : re.sub(r'[^a-zA-Z0-9]', '', "Halo, apa kabar semua")
  }

  response_data = jsonify(json_response)
  return response_data

if __name__ == '__main__':
  app.run()